config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "consultations#index"

  resources :doctors
  resources :patients
  resources :consultations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/consultation.rb
class Consultation < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
end

app/models/doctor.rb
class Doctor < ApplicationRecord
end

app/models/patient.rb
class Patient < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/consultations_controller.rb
class ConsultationsController < ApplicationController

  def index
    @consultations = Consultation.all
  end

  def show
    @consultation = Consultation.find(params[:id])
  end

  def new
    @consultation = Consultation.new
    @doctors = Doctor.all
    @patients = Patient.all
  end

  def create
    @consultation = Consultation.new(consultation_params)
    if @consultation.save
      redirect_to consultations_path(@consultation)
    else
      render :new
    end
  end

  def destroy
    @consultation = Consultation.find(params[:id])
    @consultation.destroy

    redirect_to root_path, status: :see_other
  end

  def edit
    @doctors = Doctor.all
    @patients = Patient.all
    @consultation = Consultation.find(params[:id])
  end

  def update
    @consultation = Consultation.find(params[:id])
    @consultation.update(consultation_params)

    redirect_to consultation_path(@consultation)
  end

  private

  def consultation_params
    params.require(:consultation).permit(:name, :doctor_id, :patient_id)
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  def index
    @doctors = Doctor.all
  end

  def show
    @doctor = Doctor.find(params[:id])
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(doctor_params)
    if @doctor.save
      redirect_to doctors_path(@consultation)
    else
      render :new
    end
  end

  def destroy
    @doctor = Doctor.find(params[:id])
    @doctor.destroy

    redirect_to doctors_path, status: :see_other
  end

  def edit
    @doctor = Doctor.find(params[:id])
  end

  def update
    @doctor = Doctor.find(params[:id])
    @doctor.update(doctor_params)

    redirect_to doctor_path(@doctor)
  end

  private

  def doctor_params
    params.require(:doctor).permit(:first_name, :last_name, :speciality)
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
    @patients = Patient.all
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    if @patient.save
      redirect_to patients_path(@consultation)
    else
      render :new
    end
  end

  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy

    redirect_to patients_path, status: :see_other
  end

  def edit
    @patients = Patient.all
    @patient = Patient.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:id])
    @patient.update(patient_params)

    redirect_to patient_path(@patient)
  end

  private

  def patient_params
    params.require(:patient).permit(:first_name, :last_name, :social_security_number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consultations_helper.rb
module ConsultationsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/consultations/consultations/edit.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-5 shadow">
        <h1>Edit your consultation</h1>
        <%= simple_form_for @consultation do |f| %>
          <%= f.input :name, placeholder: 'Henri Dupont' %>
          <%= f.association :doctor, collection: @doctors, :label_method => :last_name, :value_method => :id, :include_blank => false, prompt: "Select a doctor", input_html: { data: { controller: "slect2" } } %>
          <%= f.association :patient, collection: @patients, :label_method => :last_name, :value_method => :id, :include_blank => false, prompt: "Select a patient", input_html: { data: { controller: "slect2" } } %>
          <%= f.submit class: 'btn btn-success m-1' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/consultations/consultations/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-5 shadow">
        <h3>Create a new consultation</h3>
        <%= simple_form_for @consultation do |f| %>
          <%= f.input :name, placeholder: 'Henri Dupont',
                      required: true,
                      autofocus: true %>
          <%= f.association :doctor, collection: @doctors, :label_method => :last_name, :value_method => :id, :include_blank => false, prompt: "Select a doctor", input_html: { data: { controller: "slect2" } } %>
          <%= f.association :patient, collection: @patients, :label_method => :last_name, :value_method => :id, :include_blank => false, prompt: "Select a patient", input_html: { data: { controller: "slect2" } } %>
          <%= f.submit class: "btn btn-success m-1" %>
        <% end %>
        <%= link_to 'Back', root_path, class: 'btn btn-primary m-1' %>
      </div>
    </div>
  </div>
</div>

app/views/consultations/edit.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12">
      <div class="bg-white rounded p-5 m-5 shadow h-100 position-relative">
        <h1 class="mb-5 d-flex justify-content-center">Edit your consultation</h1>
        <div class="d-flex justify-content-center w-100">
          <%= simple_form_for @consultation do |f| %>
            <%= f.association :doctor, collection: @doctors, :label_method => :last_name, :value_method => :id, :include_blank => false, prompt: "Select a doctor", input_html: { data: { controller: "slect2" } } %>
            <%= f.association :patient, collection: @patients, :label_method => :last_name, :value_method => :id, :include_blank => false, prompt: "Select a patient", input_html: { data: { controller: "slect2" } } %>
            <%= f.submit class: 'btn btn-light shadow mt-2 mb-2 p-3 w-100' %>
          <% end %>
        </div>
        <div class="d-flex justify-content-end position-absolute bottom-0 end-0 p-3">
          <%= link_to 'Back', root_path, class: 'btn btn-light shadow mt-5 me-3 p-3' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/consultations/index.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12">
      <div class="bg-white rounded p-5 m-5 shadow h-100 position-relative">
        <h1 class="mb-5">My consultations</h1>

        <div class="row">
            <% @consultations.each do |consultation| %>
              <div>
                <%= link_to consultation_path(consultation), class: "btn btn-light shadow mt-2 mb-2" do %>
                  <div class="p-3">Dr. <%= consultation.doctor.last_name %> and patient <%= consultation.patient.last_name %></div>
                <% end %>
              </div>
            <% end %>
          </div>
        <div class="d-flex justify-content-end position-absolute bottom-0 end-0 p-3">
          <%= link_to "New consultation", new_consultation_path, class: "btn btn-light shadow mt-5 me-3 p-3" %>
          <%= link_to "Doctors", doctors_path, class: "btn btn-light shadow mt-5 me-3 p-3" %>
          <%= link_to "Patients", patients_path, class: "btn btn-light shadow mt-5 p-3" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/consultations/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12">
      <div class="bg-white rounded p-5 m-5 shadow h-100 position-relative">
        <h3 class="mb-5 d-flex justify-content-center">Create consultation</h3>
        <div class="d-flex justify-content-center w-100">
          <%= simple_form_for @consultation do |f| %>
            <%= f.association :doctor, collection: @doctors, :label_method => :last_name, :value_method => :id, :include_blank => false, prompt: "Select a doctor", input_html: { data: { controller: "slect2" } } %>
            <%= f.association :patient, collection: @patients, :label_method => :last_name, :value_method => :id, :include_blank => false, prompt: "Select a patient", input_html: { data: { controller: "slect2" } } %>
            <%= f.submit class: "btn btn-light shadow mt-2 mb-2 p-3 w-100" %>
          <% end %>
        </div>
        <div class="d-flex justify-content-end position-absolute bottom-0 end-0 p-3">
          <%= link_to 'Create Doctor', new_doctor_path, class: 'btn btn-light shadow mt-5 me-3 p-3' %>
          <%= link_to 'Create Patient', new_patient_path, class: 'btn btn-light shadow mt-5 me-3 p-3' %>
          <%= link_to 'Back', root_path, class: 'btn btn-light shadow mt-5 me-3 p-3' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/consultations/show.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12">
      <div class="bg-white rounded p-5 m-5 shadow h-100 position-relative">
        <h1 class="mb-5">Consultation</h1>
        <h2 class="h4">Between Doctor <%= @consultation.doctor.last_name %> (<%= @consultation.doctor.speciality %>) and the patient <%= @consultation.patient.last_name %>.</h2>

        <div class="d-flex justify-content-end position-absolute bottom-0 end-0 p-3">
          <%= link_to "Delete", consultation_path(@consultation), data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                    }, class: 'btn btn-danger shadow mt-5 me-3 p-3' %>
          <%= link_to 'Edit', edit_consultation_path, class: 'btn btn-light shadow mt-5 me-3 p-3' %>
          <%= link_to 'Back', root_path, class: 'btn btn-light shadow mt-5 me-3 p-3' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/doctors/doctors/edit.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Edit Doctor</h3>
        <%= simple_form_for @doctor do |f| %>
          <%= f.input :first_name, placeholder: 'Henri' %>
          <%= f.input :last_name, placeholder: 'Dupont' %>
          <%= f.input :speciality, placeholder: 'Dentist' %>

          <%= f.submit class: 'btn btn-success m-1' %>
        <% end %>
        <%= link_to 'Back', new_consultation_path, class: 'btn btn-primary m-1' %>
      </div>
    </div>
  </div>
</div>

app/views/doctors/doctors/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Create a new Doctor</h3>
        <%= simple_form_for @doctor do |f| %>
          <%= f.input :first_name, placeholder: 'Henri' %>
          <%= f.input :last_name, placeholder: 'Dupont' %>
          <%= f.input :speciality, placeholder: 'Dentist' %>

          <%= f.submit class: 'btn btn-success m-1' %>
        <% end %>
        <%= link_to 'Back', doctors_path, class: 'btn btn-primary m-1' %>
      </div>
    </div>
  </div>
</div>

app/views/doctors/edit.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12">
      <div class="bg-white rounded p-5 m-5 shadow h-100 position-relative">
        <h3 class="mb-5 d-flex justify-content-center">Edit Doctor</h3>
        <div class="d-flex justify-content-center w-100">
          <%= simple_form_for @doctor do |f| %>
            <%= f.input :first_name, placeholder: 'Henri' %>
            <%= f.input :last_name, placeholder: 'Dupont' %>
            <%= f.input :speciality, placeholder: 'Dentist' %>

            <%= f.submit class: 'btn btn-light shadow mt-2 mb-2 p-3' %>
          <% end %>
        </div>
        <div class="d-flex justify-content-end position-absolute bottom-0 end-0 p-3">
          <%= link_to 'Back', new_consultation_path, class: 'btn btn-light shadow mt-5 me-3 p-3' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/doctors/index.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12">
      <div class="bg-white rounded p-5 m-5 shadow h-100 position-relative">
        <h1 class="mb-5">Doctors</h1>

        <div class="row">
            <% @doctors.each do |doctor| %>
              <div>
                <%= link_to doctor_path(doctor), class: "btn btn-light shadow mt-2 mb-2" do %>
                    <div class="p-3">Dr. <%= doctor.last_name %></div>
                <% end %>
              </div>
            <% end %>
          </div>
        <div class="d-flex justify-content-end position-absolute bottom-0 end-0 p-3">
          <%= link_to 'Create Doctor', new_doctor_path, class: 'btn btn-light shadow mt-5 me-3 p-3' %>
          <%= link_to 'Back', root_path, class: 'btn btn-light shadow mt-5 me-3 p-3' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/doctors/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12">
      <div class="bg-white rounded p-5 m-5 shadow h-100 position-relative">
        <h3 class="mb-5 d-flex justify-content-center">Create a new Doctor</h3>
        <div class="d-flex justify-content-center w-100">
          <%= simple_form_for @doctor do |f| %>
            <%= f.input :first_name, placeholder: 'Henri' %>
            <%= f.input :last_name, placeholder: 'Dupont' %>
            <%= f.input :speciality, placeholder: 'Dentist' %>

            <%= f.submit class: "btn btn-light shadow mt-2 mb-2 p-3 w-100" %>
          <% end %>
        </div>
        <div class="d-flex justify-content-end position-absolute bottom-0 end-0 p-3">
          <%= link_to 'Back', doctors_path, class: 'btn btn-light shadow mt-5 me-3 p-3' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/doctors/show.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12">
      <div class="bg-white rounded p-5 m-5 shadow h-100 position-relative">
        <h1 class="mb-2">Dr. <%= @doctor.last_name %></h1>
          <h2 class="mb-5 h3"><%= @doctor.speciality %></h2>

        <div class="d-flex justify-content-end position-absolute bottom-0 end-0 p-3">
          <%= link_to "Delete", doctor_path(@doctor), data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                    }, class: 'btn btn-danger shadow mt-5 me-3 p-3' %>

          <%= link_to 'Edit', edit_doctor_path, class: 'btn btn-light shadow mt-5 me-3 p-3' %>
          <%= link_to 'Back', doctors_path, class: 'btn btn-light shadow mt-5 me-3 p-3' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Consulteo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <%= yield %>
  </body>
    <%= render partial: "shared/footer" %>
</html>

app/views/patients/edit.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12">
      <div class="bg-white rounded p-5 m-5 shadow h-100 position-relative">
        <h3 class="mb-5 d-flex justify-content-center">Edit Patient</h3>
        <div class="d-flex justify-content-center w-100">
          <%= simple_form_for @patient do |f| %>
            <%= f.input :first_name, placeholder: 'Henri' %>
            <%= f.input :last_name, placeholder: 'Dupont' %>
            <%= f.input :social_security_number, placeholder: '1243' %>
            <%= f.submit class: 'btn btn-light shadow mt-2 mb-2 p-3' %>
          <% end %>
        </div>
        <div class="d-flex justify-content-end position-absolute bottom-0 end-0 p-3">
          <%= link_to 'Back', patients_path, class: 'btn btn-light shadow mt-5 me-3 p-3' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/patients/index.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12">
      <div class="bg-white rounded p-5 m-5 shadow h-100 position-relative">
        <h1 class="mb-5">Patients</h1>

        <div class="row">
            <% @patients.each do |patient| %>
              <div>
                <%= link_to patient_path(patient), class: "btn btn-light shadow mt-2 mb-2" do %>
                  <div class="p-3"><%= patient.last_name %></div>
                <% end %>
              </div>
            <% end %>
          </div>
        <div class="d-flex justify-content-end position-absolute bottom-0 end-0 p-3">
          <%= link_to 'Create Patient', new_patient_path, class: 'btn btn-light shadow mt-5 me-3 p-3' %>
          <%= link_to 'Back', root_path, class: 'btn btn-light shadow mt-5 me-3 p-3' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/patients/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12">
      <div class="bg-white rounded p-5 m-5 shadow h-100 position-relative">
        <h3 class="mb-5 d-flex justify-content-center">Create Patient</h3>
        <div class="d-flex justify-content-center w-100">
          <%= simple_form_for @patient do |f| %>
            <%= f.input :first_name, placeholder: 'Henri' %>
            <%= f.input :last_name, placeholder: 'Dupont' %>
            <%= f.input :social_security_number, placeholder: '1243' %>

            <%= f.submit class: 'btn btn-light shadow mt-2 mb-2 p-3' %>
          <% end %>
        </div>
        <div class="d-flex justify-content-end position-absolute bottom-0 end-0 p-3">
          <%= link_to 'Back', patients_path, class: 'btn btn-light shadow mt-5 me-3 p-3' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/patients/patients/edit.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Edit Patient</h3>
        <%= simple_form_for @patient do |f| %>
          <%= f.input :first_name, placeholder: 'Henri' %>
          <%= f.input :last_name, placeholder: 'Dupont' %>
          <%= f.input :social_security_number, placeholder: '1243' %>
          <%= f.submit class: 'btn btn-success m-1' %>
        <% end %>
        <%= link_to 'Back', patients_path, class: 'btn btn-primary m-1' %>
      </div>
    </div>
  </div>
</div>

app/views/patients/patients/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Create a new Patient</h3>
        <%= simple_form_for @patient do |f| %>
          <%= f.input :first_name, placeholder: 'Henri' %>
          <%= f.input :last_name, placeholder: 'Dupont' %>
          <%= f.input :social_security_number, placeholder: '1243' %>

          <%= f.submit class: 'btn btn-success m-1' %>
        <% end %>
        <%= link_to 'Back', patients_path, class: 'btn btn-primary m-1' %>
      </div>
    </div>
  </div>
</div>

app/views/patients/patients/show.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-5 shadow">
        <h1><%= @patient.last_name %></h1>
        <%= link_to "Supprimer", patient_path(@patient), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger m-1' %>
        <%= link_to 'Edit', edit_patient_path, class: 'btn btn-secondary m-1' %>
        <%= link_to 'Back', patients_path, class: 'btn btn-primary m-1' %>
      </div>
    </div>
  </div>
</div>

app/views/patients/show.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12">
      <div class="bg-white rounded p-5 m-5 shadow h-100 position-relative">
        <h1 class="mb-5"><%= @patient.last_name %></h1>

        <div class="d-flex justify-content-end position-absolute bottom-0 end-0 p-3">
          <%= link_to "Delete", patient_path(@patient), data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                    }, class: 'btn btn-danger shadow mt-5 me-3 p-3' %>

          <%= link_to 'Edit', edit_patient_path, class: 'btn btn-light shadow mt-5 me-3 p-3' %>
          <%= link_to 'Back', patients_path, class: 'btn btn-light shadow mt-5 me-3 p-3' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

<footer class="footer_area section_padding_130_0">
      <div class="container">
        <div class="row">
          <!-- Single Widget-->
          <div class="col-12 col-sm-6 col-lg-4">
            <div class="single-footer-widget section_padding_0_130">
              <!-- Footer Logo-->
              <div class="footer-logo mb-3"></div>
              <p>Appland is completely creative, lightweight, clean app landing page.</p>
              <!-- Copywrite Text-->
              <div class="copywrite-text mb-5">
                <p class="mb-0">Made with love by <a class="ml-1" href="https://wrapbootstrap.com/user/DesigningWorld">Designing World</a></p>
              </div>
              <!-- Footer Social Area-->
              <div class="footer_social_area"><a href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="Facebook"><i class="fa fa-facebook"></i></a><a href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="Pinterest"><i class="fa fa-pinterest"></i></a><a href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="Skype"><i class="fa fa-skype"></i></a><a href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="Twitter"><i class="fa fa-twitter"></i></a></div>
            </div>
          </div>
          <!-- Single Widget-->
          <div class="col-12 col-sm-6 col-lg">
            <div class="single-footer-widget section_padding_0_130">
              <!-- Widget Title-->
              <h5 class="widget-title">About</h5>
              <!-- Footer Menu-->
              <div class="footer_menu">
                <ul>
                  <li><a href="#">About Us</a></li>
                  <li><a href="#">Corporate Sale</a></li>
                  <li><a href="#">Terms &amp; Policy</a></li>
                  <li><a href="#">Community</a></li>
                </ul>
              </div>
            </div>
          </div>
          <!-- Single Widget-->
          <div class="col-12 col-sm-6 col-lg">
            <div class="single-footer-widget section_padding_0_130">
              <!-- Widget Title-->
              <h5 class="widget-title">Support</h5>
              <!-- Footer Menu-->
              <div class="footer_menu">
                <ul>
                  <li><a href="#">Help</a></li>
                  <li><a href="#">Support</a></li>
                  <li><a href="#">Privacy Policy</a></li>
                  <li><a href="#">Term &amp; Conditions</a></li>
                  <li><a href="#">Help &amp; Support</a></li>
                </ul>
              </div>
            </div>
          </div>
          <!-- Single Widget-->
          <div class="col-12 col-sm-6 col-lg">
            <div class="single-footer-widget section_padding_0_130">
              <!-- Widget Title-->
              <h5 class="widget-title">Contact</h5>
              <!-- Footer Menu-->
              <div class="footer_menu">
                <ul>
                  <li><a href="#">Call Centre</a></li>
                  <li><a href="#">Email Us</a></li>
                  <li><a href="#">Term &amp; Conditions</a></li>
                  <li><a href="#">Help Center</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light shadow-nav">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Consulteo</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= link_to 'Consultations', consultations_path, class: 'nav-link' %>
        <%= link_to 'Doctors', doctors_path, class: 'nav-link' %>
        <%= link_to 'Patients', patients_path, class: 'nav-link' %>
      </div>
    </div>
  </div>
</nav>